package com.geekstudy.orange.db.example;

import com.geekstudy.orange.db.model.GeekMaterial;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class GeekMaterialExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer rows;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    public GeekMaterialExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public GeekMaterialExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public GeekMaterialExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public GeekMaterialExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public GeekMaterialExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public GeekMaterialExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMaterialIdIsNull() {
            addCriterion("material_id is null");
            return (Criteria) this;
        }

        public Criteria andMaterialIdIsNotNull() {
            addCriterion("material_id is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialIdEqualTo(Integer value) {
            addCriterion("material_id =", value, "materialId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialIdEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotEqualTo(Integer value) {
            addCriterion("material_id <>", value, "materialId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialIdNotEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialIdGreaterThan(Integer value) {
            addCriterion("material_id >", value, "materialId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialIdGreaterThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("material_id >=", value, "materialId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialIdGreaterThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialIdLessThan(Integer value) {
            addCriterion("material_id <", value, "materialId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialIdLessThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialIdLessThanOrEqualTo(Integer value) {
            addCriterion("material_id <=", value, "materialId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialIdLessThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialIdIn(List<Integer> values) {
            addCriterion("material_id in", values, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotIn(List<Integer> values) {
            addCriterion("material_id not in", values, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdBetween(Integer value1, Integer value2) {
            addCriterion("material_id between", value1, value2, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotBetween(Integer value1, Integer value2) {
            addCriterion("material_id not between", value1, value2, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialNameIsNull() {
            addCriterion("material_name is null");
            return (Criteria) this;
        }

        public Criteria andMaterialNameIsNotNull() {
            addCriterion("material_name is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialNameEqualTo(String value) {
            addCriterion("material_name =", value, "materialName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialNameEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotEqualTo(String value) {
            addCriterion("material_name <>", value, "materialName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialNameNotEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialNameGreaterThan(String value) {
            addCriterion("material_name >", value, "materialName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialNameGreaterThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialNameGreaterThanOrEqualTo(String value) {
            addCriterion("material_name >=", value, "materialName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialNameGreaterThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialNameLessThan(String value) {
            addCriterion("material_name <", value, "materialName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialNameLessThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialNameLessThanOrEqualTo(String value) {
            addCriterion("material_name <=", value, "materialName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialNameLessThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialNameLike(String value) {
            addCriterion("material_name like", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotLike(String value) {
            addCriterion("material_name not like", value, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameIn(List<String> values) {
            addCriterion("material_name in", values, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotIn(List<String> values) {
            addCriterion("material_name not in", values, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameBetween(String value1, String value2) {
            addCriterion("material_name between", value1, value2, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialNameNotBetween(String value1, String value2) {
            addCriterion("material_name not between", value1, value2, "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialTitleIsNull() {
            addCriterion("material_title is null");
            return (Criteria) this;
        }

        public Criteria andMaterialTitleIsNotNull() {
            addCriterion("material_title is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialTitleEqualTo(String value) {
            addCriterion("material_title =", value, "materialTitle");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialTitleEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_title = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialTitleNotEqualTo(String value) {
            addCriterion("material_title <>", value, "materialTitle");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialTitleNotEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_title <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialTitleGreaterThan(String value) {
            addCriterion("material_title >", value, "materialTitle");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialTitleGreaterThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_title > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialTitleGreaterThanOrEqualTo(String value) {
            addCriterion("material_title >=", value, "materialTitle");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialTitleGreaterThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_title >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialTitleLessThan(String value) {
            addCriterion("material_title <", value, "materialTitle");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialTitleLessThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_title < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialTitleLessThanOrEqualTo(String value) {
            addCriterion("material_title <=", value, "materialTitle");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialTitleLessThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_title <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialTitleLike(String value) {
            addCriterion("material_title like", value, "materialTitle");
            return (Criteria) this;
        }

        public Criteria andMaterialTitleNotLike(String value) {
            addCriterion("material_title not like", value, "materialTitle");
            return (Criteria) this;
        }

        public Criteria andMaterialTitleIn(List<String> values) {
            addCriterion("material_title in", values, "materialTitle");
            return (Criteria) this;
        }

        public Criteria andMaterialTitleNotIn(List<String> values) {
            addCriterion("material_title not in", values, "materialTitle");
            return (Criteria) this;
        }

        public Criteria andMaterialTitleBetween(String value1, String value2) {
            addCriterion("material_title between", value1, value2, "materialTitle");
            return (Criteria) this;
        }

        public Criteria andMaterialTitleNotBetween(String value1, String value2) {
            addCriterion("material_title not between", value1, value2, "materialTitle");
            return (Criteria) this;
        }

        public Criteria andMaterialViewIsNull() {
            addCriterion("material_view is null");
            return (Criteria) this;
        }

        public Criteria andMaterialViewIsNotNull() {
            addCriterion("material_view is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialViewEqualTo(Integer value) {
            addCriterion("material_view =", value, "materialView");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialViewEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_view = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialViewNotEqualTo(Integer value) {
            addCriterion("material_view <>", value, "materialView");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialViewNotEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_view <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialViewGreaterThan(Integer value) {
            addCriterion("material_view >", value, "materialView");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialViewGreaterThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_view > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialViewGreaterThanOrEqualTo(Integer value) {
            addCriterion("material_view >=", value, "materialView");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialViewGreaterThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_view >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialViewLessThan(Integer value) {
            addCriterion("material_view <", value, "materialView");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialViewLessThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_view < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialViewLessThanOrEqualTo(Integer value) {
            addCriterion("material_view <=", value, "materialView");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialViewLessThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_view <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialViewIn(List<Integer> values) {
            addCriterion("material_view in", values, "materialView");
            return (Criteria) this;
        }

        public Criteria andMaterialViewNotIn(List<Integer> values) {
            addCriterion("material_view not in", values, "materialView");
            return (Criteria) this;
        }

        public Criteria andMaterialViewBetween(Integer value1, Integer value2) {
            addCriterion("material_view between", value1, value2, "materialView");
            return (Criteria) this;
        }

        public Criteria andMaterialViewNotBetween(Integer value1, Integer value2) {
            addCriterion("material_view not between", value1, value2, "materialView");
            return (Criteria) this;
        }

        public Criteria andMaterialCreatetimeIsNull() {
            addCriterion("material_createTime is null");
            return (Criteria) this;
        }

        public Criteria andMaterialCreatetimeIsNotNull() {
            addCriterion("material_createTime is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialCreatetimeEqualTo(LocalDateTime value) {
            addCriterion("material_createTime =", value, "materialCreatetime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialCreatetimeEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_createTime = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialCreatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("material_createTime <>", value, "materialCreatetime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialCreatetimeNotEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_createTime <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialCreatetimeGreaterThan(LocalDateTime value) {
            addCriterion("material_createTime >", value, "materialCreatetime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialCreatetimeGreaterThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_createTime > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialCreatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("material_createTime >=", value, "materialCreatetime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialCreatetimeGreaterThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_createTime >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialCreatetimeLessThan(LocalDateTime value) {
            addCriterion("material_createTime <", value, "materialCreatetime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialCreatetimeLessThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_createTime < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialCreatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("material_createTime <=", value, "materialCreatetime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialCreatetimeLessThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_createTime <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialCreatetimeIn(List<LocalDateTime> values) {
            addCriterion("material_createTime in", values, "materialCreatetime");
            return (Criteria) this;
        }

        public Criteria andMaterialCreatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("material_createTime not in", values, "materialCreatetime");
            return (Criteria) this;
        }

        public Criteria andMaterialCreatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("material_createTime between", value1, value2, "materialCreatetime");
            return (Criteria) this;
        }

        public Criteria andMaterialCreatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("material_createTime not between", value1, value2, "materialCreatetime");
            return (Criteria) this;
        }

        public Criteria andMaterialThumbIsNull() {
            addCriterion("material_thumb is null");
            return (Criteria) this;
        }

        public Criteria andMaterialThumbIsNotNull() {
            addCriterion("material_thumb is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialThumbEqualTo(String value) {
            addCriterion("material_thumb =", value, "materialThumb");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialThumbEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_thumb = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialThumbNotEqualTo(String value) {
            addCriterion("material_thumb <>", value, "materialThumb");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialThumbNotEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_thumb <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialThumbGreaterThan(String value) {
            addCriterion("material_thumb >", value, "materialThumb");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialThumbGreaterThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_thumb > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialThumbGreaterThanOrEqualTo(String value) {
            addCriterion("material_thumb >=", value, "materialThumb");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialThumbGreaterThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_thumb >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialThumbLessThan(String value) {
            addCriterion("material_thumb <", value, "materialThumb");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialThumbLessThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_thumb < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialThumbLessThanOrEqualTo(String value) {
            addCriterion("material_thumb <=", value, "materialThumb");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialThumbLessThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_thumb <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialThumbLike(String value) {
            addCriterion("material_thumb like", value, "materialThumb");
            return (Criteria) this;
        }

        public Criteria andMaterialThumbNotLike(String value) {
            addCriterion("material_thumb not like", value, "materialThumb");
            return (Criteria) this;
        }

        public Criteria andMaterialThumbIn(List<String> values) {
            addCriterion("material_thumb in", values, "materialThumb");
            return (Criteria) this;
        }

        public Criteria andMaterialThumbNotIn(List<String> values) {
            addCriterion("material_thumb not in", values, "materialThumb");
            return (Criteria) this;
        }

        public Criteria andMaterialThumbBetween(String value1, String value2) {
            addCriterion("material_thumb between", value1, value2, "materialThumb");
            return (Criteria) this;
        }

        public Criteria andMaterialThumbNotBetween(String value1, String value2) {
            addCriterion("material_thumb not between", value1, value2, "materialThumb");
            return (Criteria) this;
        }

        public Criteria andMaterialTagIsNull() {
            addCriterion("material_tag is null");
            return (Criteria) this;
        }

        public Criteria andMaterialTagIsNotNull() {
            addCriterion("material_tag is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialTagEqualTo(String value) {
            addCriterion("material_tag =", value, "materialTag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialTagEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_tag = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialTagNotEqualTo(String value) {
            addCriterion("material_tag <>", value, "materialTag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialTagNotEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_tag <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialTagGreaterThan(String value) {
            addCriterion("material_tag >", value, "materialTag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialTagGreaterThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_tag > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialTagGreaterThanOrEqualTo(String value) {
            addCriterion("material_tag >=", value, "materialTag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialTagGreaterThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_tag >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialTagLessThan(String value) {
            addCriterion("material_tag <", value, "materialTag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialTagLessThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_tag < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialTagLessThanOrEqualTo(String value) {
            addCriterion("material_tag <=", value, "materialTag");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialTagLessThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_tag <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialTagLike(String value) {
            addCriterion("material_tag like", value, "materialTag");
            return (Criteria) this;
        }

        public Criteria andMaterialTagNotLike(String value) {
            addCriterion("material_tag not like", value, "materialTag");
            return (Criteria) this;
        }

        public Criteria andMaterialTagIn(List<String> values) {
            addCriterion("material_tag in", values, "materialTag");
            return (Criteria) this;
        }

        public Criteria andMaterialTagNotIn(List<String> values) {
            addCriterion("material_tag not in", values, "materialTag");
            return (Criteria) this;
        }

        public Criteria andMaterialTagBetween(String value1, String value2) {
            addCriterion("material_tag between", value1, value2, "materialTag");
            return (Criteria) this;
        }

        public Criteria andMaterialTagNotBetween(String value1, String value2) {
            addCriterion("material_tag not between", value1, value2, "materialTag");
            return (Criteria) this;
        }

        public Criteria andMaterialEditorIsNull() {
            addCriterion("material_editor is null");
            return (Criteria) this;
        }

        public Criteria andMaterialEditorIsNotNull() {
            addCriterion("material_editor is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialEditorEqualTo(String value) {
            addCriterion("material_editor =", value, "materialEditor");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialEditorEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_editor = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialEditorNotEqualTo(String value) {
            addCriterion("material_editor <>", value, "materialEditor");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialEditorNotEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_editor <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialEditorGreaterThan(String value) {
            addCriterion("material_editor >", value, "materialEditor");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialEditorGreaterThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_editor > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialEditorGreaterThanOrEqualTo(String value) {
            addCriterion("material_editor >=", value, "materialEditor");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialEditorGreaterThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_editor >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialEditorLessThan(String value) {
            addCriterion("material_editor <", value, "materialEditor");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialEditorLessThanColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_editor < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialEditorLessThanOrEqualTo(String value) {
            addCriterion("material_editor <=", value, "materialEditor");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaterialEditorLessThanOrEqualToColumn(GeekMaterial.Column column) {
            addCriterion(new StringBuilder("material_editor <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaterialEditorLike(String value) {
            addCriterion("material_editor like", value, "materialEditor");
            return (Criteria) this;
        }

        public Criteria andMaterialEditorNotLike(String value) {
            addCriterion("material_editor not like", value, "materialEditor");
            return (Criteria) this;
        }

        public Criteria andMaterialEditorIn(List<String> values) {
            addCriterion("material_editor in", values, "materialEditor");
            return (Criteria) this;
        }

        public Criteria andMaterialEditorNotIn(List<String> values) {
            addCriterion("material_editor not in", values, "materialEditor");
            return (Criteria) this;
        }

        public Criteria andMaterialEditorBetween(String value1, String value2) {
            addCriterion("material_editor between", value1, value2, "materialEditor");
            return (Criteria) this;
        }

        public Criteria andMaterialEditorNotBetween(String value1, String value2) {
            addCriterion("material_editor not between", value1, value2, "materialEditor");
            return (Criteria) this;
        }

        public Criteria andMaterialNameLikeInsensitive(String value) {
            addCriterion("upper(material_name) like", value.toUpperCase(), "materialName");
            return (Criteria) this;
        }

        public Criteria andMaterialTitleLikeInsensitive(String value) {
            addCriterion("upper(material_title) like", value.toUpperCase(), "materialTitle");
            return (Criteria) this;
        }

        public Criteria andMaterialThumbLikeInsensitive(String value) {
            addCriterion("upper(material_thumb) like", value.toUpperCase(), "materialThumb");
            return (Criteria) this;
        }

        public Criteria andMaterialTagLikeInsensitive(String value) {
            addCriterion("upper(material_tag) like", value.toUpperCase(), "materialTag");
            return (Criteria) this;
        }

        public Criteria andMaterialEditorLikeInsensitive(String value) {
            addCriterion("upper(material_editor) like", value.toUpperCase(), "materialEditor");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table geek_material
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private GeekMaterialExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(GeekMaterialExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public GeekMaterialExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table geek_material
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}