package com.geekstudy.orange.db.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table geek_coursevideo
 */
public class GeekCoursevideo {
    /**
     * Database Column Remarks:
     *   课程id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_coursevideo.video_id
     *
     * @mbg.generated
     */
    private Integer videoId;

    /**
     * Database Column Remarks:
     *   教学视频名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_coursevideo.video_name
     *
     * @mbg.generated
     */
    private String videoName;

    /**
     * Database Column Remarks:
     *   教学视频标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_coursevideo.video_title
     *
     * @mbg.generated
     */
    private String videoTitle;

    /**
     * Database Column Remarks:
     *   视频文件路径名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_coursevideo.video_url
     *
     * @mbg.generated
     */
    private String videoUrl;

    /**
     * Database Column Remarks:
     *   视频所属课程id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_coursevideo.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     * Database Column Remarks:
     *   视频上传时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_coursevideo.video_createTime
     *
     * @mbg.generated
     */
    private LocalDateTime videoCreatetime;

    /**
     * Database Column Remarks:
     *   教学视频排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_coursevideo.video_order
     *
     * @mbg.generated
     */
    private Integer videoOrder;

    /**
     * Database Column Remarks:
     *   教学视频描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_coursevideo.video_description
     *
     * @mbg.generated
     */
    private String videoDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_coursevideo.video_id
     *
     * @return the value of geek_coursevideo.video_id
     *
     * @mbg.generated
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_coursevideo.video_id
     *
     * @param videoId the value for geek_coursevideo.video_id
     *
     * @mbg.generated
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_coursevideo.video_name
     *
     * @return the value of geek_coursevideo.video_name
     *
     * @mbg.generated
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_coursevideo.video_name
     *
     * @param videoName the value for geek_coursevideo.video_name
     *
     * @mbg.generated
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName == null ? null : videoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_coursevideo.video_title
     *
     * @return the value of geek_coursevideo.video_title
     *
     * @mbg.generated
     */
    public String getVideoTitle() {
        return videoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_coursevideo.video_title
     *
     * @param videoTitle the value for geek_coursevideo.video_title
     *
     * @mbg.generated
     */
    public void setVideoTitle(String videoTitle) {
        this.videoTitle = videoTitle == null ? null : videoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_coursevideo.video_url
     *
     * @return the value of geek_coursevideo.video_url
     *
     * @mbg.generated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_coursevideo.video_url
     *
     * @param videoUrl the value for geek_coursevideo.video_url
     *
     * @mbg.generated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_coursevideo.course_id
     *
     * @return the value of geek_coursevideo.course_id
     *
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_coursevideo.course_id
     *
     * @param courseId the value for geek_coursevideo.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_coursevideo.video_createTime
     *
     * @return the value of geek_coursevideo.video_createTime
     *
     * @mbg.generated
     */
    public LocalDateTime getVideoCreatetime() {
        return videoCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_coursevideo.video_createTime
     *
     * @param videoCreatetime the value for geek_coursevideo.video_createTime
     *
     * @mbg.generated
     */
    public void setVideoCreatetime(LocalDateTime videoCreatetime) {
        this.videoCreatetime = videoCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_coursevideo.video_order
     *
     * @return the value of geek_coursevideo.video_order
     *
     * @mbg.generated
     */
    public Integer getVideoOrder() {
        return videoOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_coursevideo.video_order
     *
     * @param videoOrder the value for geek_coursevideo.video_order
     *
     * @mbg.generated
     */
    public void setVideoOrder(Integer videoOrder) {
        this.videoOrder = videoOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_coursevideo.video_description
     *
     * @return the value of geek_coursevideo.video_description
     *
     * @mbg.generated
     */
    public String getVideoDescription() {
        return videoDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_coursevideo.video_description
     *
     * @param videoDescription the value for geek_coursevideo.video_description
     *
     * @mbg.generated
     */
    public void setVideoDescription(String videoDescription) {
        this.videoDescription = videoDescription == null ? null : videoDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursevideo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", videoId=").append(videoId);
        sb.append(", videoName=").append(videoName);
        sb.append(", videoTitle=").append(videoTitle);
        sb.append(", videoUrl=").append(videoUrl);
        sb.append(", courseId=").append(courseId);
        sb.append(", videoCreatetime=").append(videoCreatetime);
        sb.append(", videoOrder=").append(videoOrder);
        sb.append(", videoDescription=").append(videoDescription);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursevideo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static GeekCoursevideo.Builder builder() {
        return new GeekCoursevideo.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table geek_coursevideo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private GeekCoursevideo obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new GeekCoursevideo();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_coursevideo.video_id
         *
         * @param videoId the value for geek_coursevideo.video_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder videoId(Integer videoId) {
            obj.setVideoId(videoId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_coursevideo.video_name
         *
         * @param videoName the value for geek_coursevideo.video_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder videoName(String videoName) {
            obj.setVideoName(videoName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_coursevideo.video_title
         *
         * @param videoTitle the value for geek_coursevideo.video_title
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder videoTitle(String videoTitle) {
            obj.setVideoTitle(videoTitle);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_coursevideo.video_url
         *
         * @param videoUrl the value for geek_coursevideo.video_url
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder videoUrl(String videoUrl) {
            obj.setVideoUrl(videoUrl);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_coursevideo.course_id
         *
         * @param courseId the value for geek_coursevideo.course_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder courseId(Integer courseId) {
            obj.setCourseId(courseId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_coursevideo.video_createTime
         *
         * @param videoCreatetime the value for geek_coursevideo.video_createTime
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder videoCreatetime(LocalDateTime videoCreatetime) {
            obj.setVideoCreatetime(videoCreatetime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_coursevideo.video_order
         *
         * @param videoOrder the value for geek_coursevideo.video_order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder videoOrder(Integer videoOrder) {
            obj.setVideoOrder(videoOrder);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_coursevideo.video_description
         *
         * @param videoDescription the value for geek_coursevideo.video_description
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder videoDescription(String videoDescription) {
            obj.setVideoDescription(videoDescription);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public GeekCoursevideo build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table geek_coursevideo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        videoId("video_id", "videoId", "INTEGER", false),
        videoName("video_name", "videoName", "VARCHAR", false),
        videoTitle("video_title", "videoTitle", "VARCHAR", false),
        videoUrl("video_url", "videoUrl", "VARCHAR", false),
        courseId("course_id", "courseId", "INTEGER", false),
        videoCreatetime("video_createTime", "videoCreatetime", "TIMESTAMP", false),
        videoOrder("video_order", "videoOrder", "INTEGER", false),
        videoDescription("video_description", "videoDescription", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_coursevideo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}