package com.geekstudy.orange.db.model;

import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table geek_admin
 */
public class GeekAdmin {
    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_admin.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_admin.admin_name
     *
     * @mbg.generated
     */
    private String adminName;

    /**
     * Database Column Remarks:
     *   用户密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_admin.admin_pass
     *
     * @mbg.generated
     */
    private String adminPass;

    /**
     * Database Column Remarks:
     *   管理员真名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_admin.admin_truename
     *
     * @mbg.generated
     */
    private String adminTruename;

    /**
     * Database Column Remarks:
     *   管理员年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_admin.admin_age
     *
     * @mbg.generated
     */
    private Integer adminAge;

    /**
     * Database Column Remarks:
     *   管理员性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_admin.admin_gender
     *
     * @mbg.generated
     */
    private Integer adminGender;

    /**
     * Database Column Remarks:
     *   管理员头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_admin.admin_thumb
     *
     * @mbg.generated
     */
    private String adminThumb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_admin.admin_id
     *
     * @return the value of geek_admin.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_admin.admin_id
     *
     * @param adminId the value for geek_admin.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_admin.admin_name
     *
     * @return the value of geek_admin.admin_name
     *
     * @mbg.generated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_admin.admin_name
     *
     * @param adminName the value for geek_admin.admin_name
     *
     * @mbg.generated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_admin.admin_pass
     *
     * @return the value of geek_admin.admin_pass
     *
     * @mbg.generated
     */
    public String getAdminPass() {
        return adminPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_admin.admin_pass
     *
     * @param adminPass the value for geek_admin.admin_pass
     *
     * @mbg.generated
     */
    public void setAdminPass(String adminPass) {
        this.adminPass = adminPass == null ? null : adminPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_admin.admin_truename
     *
     * @return the value of geek_admin.admin_truename
     *
     * @mbg.generated
     */
    public String getAdminTruename() {
        return adminTruename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_admin.admin_truename
     *
     * @param adminTruename the value for geek_admin.admin_truename
     *
     * @mbg.generated
     */
    public void setAdminTruename(String adminTruename) {
        this.adminTruename = adminTruename == null ? null : adminTruename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_admin.admin_age
     *
     * @return the value of geek_admin.admin_age
     *
     * @mbg.generated
     */
    public Integer getAdminAge() {
        return adminAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_admin.admin_age
     *
     * @param adminAge the value for geek_admin.admin_age
     *
     * @mbg.generated
     */
    public void setAdminAge(Integer adminAge) {
        this.adminAge = adminAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_admin.admin_gender
     *
     * @return the value of geek_admin.admin_gender
     *
     * @mbg.generated
     */
    public Integer getAdminGender() {
        return adminGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_admin.admin_gender
     *
     * @param adminGender the value for geek_admin.admin_gender
     *
     * @mbg.generated
     */
    public void setAdminGender(Integer adminGender) {
        this.adminGender = adminGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_admin.admin_thumb
     *
     * @return the value of geek_admin.admin_thumb
     *
     * @mbg.generated
     */
    public String getAdminThumb() {
        return adminThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_admin.admin_thumb
     *
     * @param adminThumb the value for geek_admin.admin_thumb
     *
     * @mbg.generated
     */
    public void setAdminThumb(String adminThumb) {
        this.adminThumb = adminThumb == null ? null : adminThumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_admin
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adminId=").append(adminId);
        sb.append(", adminName=").append(adminName);
        sb.append(", adminPass=").append(adminPass);
        sb.append(", adminTruename=").append(adminTruename);
        sb.append(", adminAge=").append(adminAge);
        sb.append(", adminGender=").append(adminGender);
        sb.append(", adminThumb=").append(adminThumb);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static GeekAdmin.Builder builder() {
        return new GeekAdmin.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table geek_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private GeekAdmin obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new GeekAdmin();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_admin.admin_id
         *
         * @param adminId the value for geek_admin.admin_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder adminId(Integer adminId) {
            obj.setAdminId(adminId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_admin.admin_name
         *
         * @param adminName the value for geek_admin.admin_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder adminName(String adminName) {
            obj.setAdminName(adminName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_admin.admin_pass
         *
         * @param adminPass the value for geek_admin.admin_pass
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder adminPass(String adminPass) {
            obj.setAdminPass(adminPass);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_admin.admin_truename
         *
         * @param adminTruename the value for geek_admin.admin_truename
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder adminTruename(String adminTruename) {
            obj.setAdminTruename(adminTruename);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_admin.admin_age
         *
         * @param adminAge the value for geek_admin.admin_age
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder adminAge(Integer adminAge) {
            obj.setAdminAge(adminAge);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_admin.admin_gender
         *
         * @param adminGender the value for geek_admin.admin_gender
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder adminGender(Integer adminGender) {
            obj.setAdminGender(adminGender);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_admin.admin_thumb
         *
         * @param adminThumb the value for geek_admin.admin_thumb
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder adminThumb(String adminThumb) {
            obj.setAdminThumb(adminThumb);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public GeekAdmin build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table geek_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        adminId("admin_id", "adminId", "INTEGER", false),
        adminName("admin_name", "adminName", "VARCHAR", false),
        adminPass("admin_pass", "adminPass", "VARCHAR", false),
        adminTruename("admin_truename", "adminTruename", "VARCHAR", false),
        adminAge("admin_age", "adminAge", "INTEGER", false),
        adminGender("admin_gender", "adminGender", "INTEGER", false),
        adminThumb("admin_thumb", "adminThumb", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_admin
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}