package com.geekstudy.orange.db.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table geek_course
 */
public class GeekCourse {
    /**
     * Database Column Remarks:
     *   课程id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_course.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     * Database Column Remarks:
     *   课程名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_course.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     * Database Column Remarks:
     *   课程标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_course.course_title
     *
     * @mbg.generated
     */
    private String courseTitle;

    /**
     * Database Column Remarks:
     *   开课老师
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_course.course_teacher
     *
     * @mbg.generated
     */
    private String courseTeacher;

    /**
     * Database Column Remarks:
     *   课程创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_course.course_createTime
     *
     * @mbg.generated
     */
    private LocalDateTime courseCreatetime;

    /**
     * Database Column Remarks:
     *   课程学习人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_course.course_view
     *
     * @mbg.generated
     */
    private Integer courseView;

    /**
     * Database Column Remarks:
     *   课程缩略图地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_course.course_thumb
     *
     * @mbg.generated
     */
    private String courseThumb;

    /**
     * Database Column Remarks:
     *   课程章节数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_course.course_num
     *
     * @mbg.generated
     */
    private Integer courseNum;

    /**
     * Database Column Remarks:
     *   课程所属类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_course.cate_id
     *
     * @mbg.generated
     */
    private Integer cateId;

    /**
     * Database Column Remarks:
     *   课程描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_course.course_description
     *
     * @mbg.generated
     */
    private String courseDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_course.course_id
     *
     * @return the value of geek_course.course_id
     *
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_course.course_id
     *
     * @param courseId the value for geek_course.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_course.course_name
     *
     * @return the value of geek_course.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_course.course_name
     *
     * @param courseName the value for geek_course.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_course.course_title
     *
     * @return the value of geek_course.course_title
     *
     * @mbg.generated
     */
    public String getCourseTitle() {
        return courseTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_course.course_title
     *
     * @param courseTitle the value for geek_course.course_title
     *
     * @mbg.generated
     */
    public void setCourseTitle(String courseTitle) {
        this.courseTitle = courseTitle == null ? null : courseTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_course.course_teacher
     *
     * @return the value of geek_course.course_teacher
     *
     * @mbg.generated
     */
    public String getCourseTeacher() {
        return courseTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_course.course_teacher
     *
     * @param courseTeacher the value for geek_course.course_teacher
     *
     * @mbg.generated
     */
    public void setCourseTeacher(String courseTeacher) {
        this.courseTeacher = courseTeacher == null ? null : courseTeacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_course.course_createTime
     *
     * @return the value of geek_course.course_createTime
     *
     * @mbg.generated
     */
    public LocalDateTime getCourseCreatetime() {
        return courseCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_course.course_createTime
     *
     * @param courseCreatetime the value for geek_course.course_createTime
     *
     * @mbg.generated
     */
    public void setCourseCreatetime(LocalDateTime courseCreatetime) {
        this.courseCreatetime = courseCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_course.course_view
     *
     * @return the value of geek_course.course_view
     *
     * @mbg.generated
     */
    public Integer getCourseView() {
        return courseView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_course.course_view
     *
     * @param courseView the value for geek_course.course_view
     *
     * @mbg.generated
     */
    public void setCourseView(Integer courseView) {
        this.courseView = courseView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_course.course_thumb
     *
     * @return the value of geek_course.course_thumb
     *
     * @mbg.generated
     */
    public String getCourseThumb() {
        return courseThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_course.course_thumb
     *
     * @param courseThumb the value for geek_course.course_thumb
     *
     * @mbg.generated
     */
    public void setCourseThumb(String courseThumb) {
        this.courseThumb = courseThumb == null ? null : courseThumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_course.course_num
     *
     * @return the value of geek_course.course_num
     *
     * @mbg.generated
     */
    public Integer getCourseNum() {
        return courseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_course.course_num
     *
     * @param courseNum the value for geek_course.course_num
     *
     * @mbg.generated
     */
    public void setCourseNum(Integer courseNum) {
        this.courseNum = courseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_course.cate_id
     *
     * @return the value of geek_course.cate_id
     *
     * @mbg.generated
     */
    public Integer getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_course.cate_id
     *
     * @param cateId the value for geek_course.cate_id
     *
     * @mbg.generated
     */
    public void setCateId(Integer cateId) {
        this.cateId = cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_course.course_description
     *
     * @return the value of geek_course.course_description
     *
     * @mbg.generated
     */
    public String getCourseDescription() {
        return courseDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_course.course_description
     *
     * @param courseDescription the value for geek_course.course_description
     *
     * @mbg.generated
     */
    public void setCourseDescription(String courseDescription) {
        this.courseDescription = courseDescription == null ? null : courseDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", courseId=").append(courseId);
        sb.append(", courseName=").append(courseName);
        sb.append(", courseTitle=").append(courseTitle);
        sb.append(", courseTeacher=").append(courseTeacher);
        sb.append(", courseCreatetime=").append(courseCreatetime);
        sb.append(", courseView=").append(courseView);
        sb.append(", courseThumb=").append(courseThumb);
        sb.append(", courseNum=").append(courseNum);
        sb.append(", cateId=").append(cateId);
        sb.append(", courseDescription=").append(courseDescription);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static GeekCourse.Builder builder() {
        return new GeekCourse.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table geek_course
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private GeekCourse obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new GeekCourse();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_course.course_id
         *
         * @param courseId the value for geek_course.course_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder courseId(Integer courseId) {
            obj.setCourseId(courseId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_course.course_name
         *
         * @param courseName the value for geek_course.course_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder courseName(String courseName) {
            obj.setCourseName(courseName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_course.course_title
         *
         * @param courseTitle the value for geek_course.course_title
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder courseTitle(String courseTitle) {
            obj.setCourseTitle(courseTitle);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_course.course_teacher
         *
         * @param courseTeacher the value for geek_course.course_teacher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder courseTeacher(String courseTeacher) {
            obj.setCourseTeacher(courseTeacher);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_course.course_createTime
         *
         * @param courseCreatetime the value for geek_course.course_createTime
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder courseCreatetime(LocalDateTime courseCreatetime) {
            obj.setCourseCreatetime(courseCreatetime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_course.course_view
         *
         * @param courseView the value for geek_course.course_view
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder courseView(Integer courseView) {
            obj.setCourseView(courseView);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_course.course_thumb
         *
         * @param courseThumb the value for geek_course.course_thumb
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder courseThumb(String courseThumb) {
            obj.setCourseThumb(courseThumb);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_course.course_num
         *
         * @param courseNum the value for geek_course.course_num
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder courseNum(Integer courseNum) {
            obj.setCourseNum(courseNum);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_course.cate_id
         *
         * @param cateId the value for geek_course.cate_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder cateId(Integer cateId) {
            obj.setCateId(cateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_course.course_description
         *
         * @param courseDescription the value for geek_course.course_description
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder courseDescription(String courseDescription) {
            obj.setCourseDescription(courseDescription);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public GeekCourse build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table geek_course
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        courseId("course_id", "courseId", "INTEGER", false),
        courseName("course_name", "courseName", "VARCHAR", false),
        courseTitle("course_title", "courseTitle", "VARCHAR", false),
        courseTeacher("course_teacher", "courseTeacher", "VARCHAR", false),
        courseCreatetime("course_createTime", "courseCreatetime", "TIMESTAMP", false),
        courseView("course_view", "courseView", "INTEGER", false),
        courseThumb("course_thumb", "courseThumb", "VARCHAR", false),
        courseNum("course_num", "courseNum", "INTEGER", false),
        cateId("cate_id", "cateId", "INTEGER", false),
        courseDescription("course_description", "courseDescription", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_course
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}