package com.geekstudy.orange.db.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table geek_material
 */
public class GeekMaterial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_material.material_id
     *
     * @mbg.generated
     */
    private Integer materialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_material.material_name
     *
     * @mbg.generated
     */
    private String materialName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_material.material_title
     *
     * @mbg.generated
     */
    private String materialTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_material.material_view
     *
     * @mbg.generated
     */
    private Integer materialView;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_material.material_createTime
     *
     * @mbg.generated
     */
    private LocalDateTime materialCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_material.material_thumb
     *
     * @mbg.generated
     */
    private String materialThumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_material.material_tag
     *
     * @mbg.generated
     */
    private String materialTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_material.material_editor
     *
     * @mbg.generated
     */
    private String materialEditor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geek_material.material_content
     *
     * @mbg.generated
     */
    private String materialContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_material.material_id
     *
     * @return the value of geek_material.material_id
     *
     * @mbg.generated
     */
    public Integer getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_material.material_id
     *
     * @param materialId the value for geek_material.material_id
     *
     * @mbg.generated
     */
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_material.material_name
     *
     * @return the value of geek_material.material_name
     *
     * @mbg.generated
     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_material.material_name
     *
     * @param materialName the value for geek_material.material_name
     *
     * @mbg.generated
     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName == null ? null : materialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_material.material_title
     *
     * @return the value of geek_material.material_title
     *
     * @mbg.generated
     */
    public String getMaterialTitle() {
        return materialTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_material.material_title
     *
     * @param materialTitle the value for geek_material.material_title
     *
     * @mbg.generated
     */
    public void setMaterialTitle(String materialTitle) {
        this.materialTitle = materialTitle == null ? null : materialTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_material.material_view
     *
     * @return the value of geek_material.material_view
     *
     * @mbg.generated
     */
    public Integer getMaterialView() {
        return materialView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_material.material_view
     *
     * @param materialView the value for geek_material.material_view
     *
     * @mbg.generated
     */
    public void setMaterialView(Integer materialView) {
        this.materialView = materialView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_material.material_createTime
     *
     * @return the value of geek_material.material_createTime
     *
     * @mbg.generated
     */
    public LocalDateTime getMaterialCreatetime() {
        return materialCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_material.material_createTime
     *
     * @param materialCreatetime the value for geek_material.material_createTime
     *
     * @mbg.generated
     */
    public void setMaterialCreatetime(LocalDateTime materialCreatetime) {
        this.materialCreatetime = materialCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_material.material_thumb
     *
     * @return the value of geek_material.material_thumb
     *
     * @mbg.generated
     */
    public String getMaterialThumb() {
        return materialThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_material.material_thumb
     *
     * @param materialThumb the value for geek_material.material_thumb
     *
     * @mbg.generated
     */
    public void setMaterialThumb(String materialThumb) {
        this.materialThumb = materialThumb == null ? null : materialThumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_material.material_tag
     *
     * @return the value of geek_material.material_tag
     *
     * @mbg.generated
     */
    public String getMaterialTag() {
        return materialTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_material.material_tag
     *
     * @param materialTag the value for geek_material.material_tag
     *
     * @mbg.generated
     */
    public void setMaterialTag(String materialTag) {
        this.materialTag = materialTag == null ? null : materialTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_material.material_editor
     *
     * @return the value of geek_material.material_editor
     *
     * @mbg.generated
     */
    public String getMaterialEditor() {
        return materialEditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_material.material_editor
     *
     * @param materialEditor the value for geek_material.material_editor
     *
     * @mbg.generated
     */
    public void setMaterialEditor(String materialEditor) {
        this.materialEditor = materialEditor == null ? null : materialEditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geek_material.material_content
     *
     * @return the value of geek_material.material_content
     *
     * @mbg.generated
     */
    public String getMaterialContent() {
        return materialContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geek_material.material_content
     *
     * @param materialContent the value for geek_material.material_content
     *
     * @mbg.generated
     */
    public void setMaterialContent(String materialContent) {
        this.materialContent = materialContent == null ? null : materialContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", materialId=").append(materialId);
        sb.append(", materialName=").append(materialName);
        sb.append(", materialTitle=").append(materialTitle);
        sb.append(", materialView=").append(materialView);
        sb.append(", materialCreatetime=").append(materialCreatetime);
        sb.append(", materialThumb=").append(materialThumb);
        sb.append(", materialTag=").append(materialTag);
        sb.append(", materialEditor=").append(materialEditor);
        sb.append(", materialContent=").append(materialContent);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static GeekMaterial.Builder builder() {
        return new GeekMaterial.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private GeekMaterial obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new GeekMaterial();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_material.material_id
         *
         * @param materialId the value for geek_material.material_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder materialId(Integer materialId) {
            obj.setMaterialId(materialId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_material.material_name
         *
         * @param materialName the value for geek_material.material_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder materialName(String materialName) {
            obj.setMaterialName(materialName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_material.material_title
         *
         * @param materialTitle the value for geek_material.material_title
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder materialTitle(String materialTitle) {
            obj.setMaterialTitle(materialTitle);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_material.material_view
         *
         * @param materialView the value for geek_material.material_view
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder materialView(Integer materialView) {
            obj.setMaterialView(materialView);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_material.material_createTime
         *
         * @param materialCreatetime the value for geek_material.material_createTime
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder materialCreatetime(LocalDateTime materialCreatetime) {
            obj.setMaterialCreatetime(materialCreatetime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_material.material_thumb
         *
         * @param materialThumb the value for geek_material.material_thumb
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder materialThumb(String materialThumb) {
            obj.setMaterialThumb(materialThumb);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_material.material_tag
         *
         * @param materialTag the value for geek_material.material_tag
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder materialTag(String materialTag) {
            obj.setMaterialTag(materialTag);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_material.material_editor
         *
         * @param materialEditor the value for geek_material.material_editor
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder materialEditor(String materialEditor) {
            obj.setMaterialEditor(materialEditor);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column geek_material.material_content
         *
         * @param materialContent the value for geek_material.material_content
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder materialContent(String materialContent) {
            obj.setMaterialContent(materialContent);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public GeekMaterial build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        materialId("material_id", "materialId", "INTEGER", false),
        materialName("material_name", "materialName", "VARCHAR", false),
        materialTitle("material_title", "materialTitle", "VARCHAR", false),
        materialView("material_view", "materialView", "INTEGER", false),
        materialCreatetime("material_createTime", "materialCreatetime", "TIMESTAMP", false),
        materialThumb("material_thumb", "materialThumb", "VARCHAR", false),
        materialTag("material_tag", "materialTag", "VARCHAR", false),
        materialEditor("material_editor", "materialEditor", "VARCHAR", false),
        materialContent("material_content", "materialContent", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table geek_material
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}