package com.geekstudy.orange.db.mapper;

import com.geekstudy.orange.db.example.GeekMaterialExample;
import com.geekstudy.orange.db.model.GeekMaterial;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface GeekMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    long countByExample(GeekMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    int deleteByExample(GeekMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer materialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    int insert(GeekMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") GeekMaterial record, @Param("selective") GeekMaterial.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekMaterial selectOneByExample(GeekMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekMaterial selectOneByExampleSelective(@Param("example") GeekMaterialExample example, @Param("selective") GeekMaterial.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekMaterial selectOneByExampleWithBLOBs(GeekMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<GeekMaterial> selectByExampleSelective(@Param("example") GeekMaterialExample example, @Param("selective") GeekMaterial.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    List<GeekMaterial> selectByExampleWithBLOBs(GeekMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    List<GeekMaterial> selectByExample(GeekMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekMaterial selectByPrimaryKeySelective(@Param("materialId") Integer materialId, @Param("selective") GeekMaterial.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    GeekMaterial selectByPrimaryKey(Integer materialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") GeekMaterial record, @Param("example") GeekMaterialExample example, @Param("selective") GeekMaterial.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") GeekMaterial record, @Param("example") GeekMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GeekMaterial record, @Param("example") GeekMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") GeekMaterial record, @Param("selective") GeekMaterial.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GeekMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GeekMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GeekMaterial> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_material
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GeekMaterial> list, @Param("selective") GeekMaterial.Column ... selective);
}