package com.geekstudy.orange.db.mapper;

import com.geekstudy.orange.db.example.GeekTeacherExample;
import com.geekstudy.orange.db.model.GeekTeacher;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface GeekTeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     */
    long countByExample(GeekTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     */
    int deleteByExample(GeekTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     */
    int insert(GeekTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") GeekTeacher record, @Param("selective") GeekTeacher.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekTeacher selectOneByExample(GeekTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekTeacher selectOneByExampleSelective(@Param("example") GeekTeacherExample example, @Param("selective") GeekTeacher.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekTeacher selectOneByExampleWithBLOBs(GeekTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<GeekTeacher> selectByExampleSelective(@Param("example") GeekTeacherExample example, @Param("selective") GeekTeacher.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     */
    List<GeekTeacher> selectByExampleWithBLOBs(GeekTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     */
    List<GeekTeacher> selectByExample(GeekTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekTeacher selectByPrimaryKeySelective(@Param("teacherId") Integer teacherId, @Param("selective") GeekTeacher.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     */
    GeekTeacher selectByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") GeekTeacher record, @Param("example") GeekTeacherExample example, @Param("selective") GeekTeacher.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") GeekTeacher record, @Param("example") GeekTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GeekTeacher record, @Param("example") GeekTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") GeekTeacher record, @Param("selective") GeekTeacher.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GeekTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GeekTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GeekTeacher> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_teacher
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GeekTeacher> list, @Param("selective") GeekTeacher.Column ... selective);
}