package com.geekstudy.orange.db.mapper;

import com.geekstudy.orange.db.example.GeekCourseExample;
import com.geekstudy.orange.db.model.GeekCourse;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface GeekCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     */
    long countByExample(GeekCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     */
    int deleteByExample(GeekCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     */
    int insert(GeekCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") GeekCourse record, @Param("selective") GeekCourse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekCourse selectOneByExample(GeekCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekCourse selectOneByExampleSelective(@Param("example") GeekCourseExample example, @Param("selective") GeekCourse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekCourse selectOneByExampleWithBLOBs(GeekCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<GeekCourse> selectByExampleSelective(@Param("example") GeekCourseExample example, @Param("selective") GeekCourse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     */
    List<GeekCourse> selectByExampleWithBLOBs(GeekCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     */
    List<GeekCourse> selectByExample(GeekCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekCourse selectByPrimaryKeySelective(@Param("courseId") Integer courseId, @Param("selective") GeekCourse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     */
    GeekCourse selectByPrimaryKey(Integer courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") GeekCourse record, @Param("example") GeekCourseExample example, @Param("selective") GeekCourse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") GeekCourse record, @Param("example") GeekCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GeekCourse record, @Param("example") GeekCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") GeekCourse record, @Param("selective") GeekCourse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GeekCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GeekCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GeekCourse> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_course
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GeekCourse> list, @Param("selective") GeekCourse.Column ... selective);
}