package com.geekstudy.orange.db.mapper;

import com.geekstudy.orange.db.example.GeekCoursecateExample;
import com.geekstudy.orange.db.model.GeekCoursecate;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface GeekCoursecateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     */
    long countByExample(GeekCoursecateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     */
    int deleteByExample(GeekCoursecateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     */
    int insert(GeekCoursecate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") GeekCoursecate record, @Param("selective") GeekCoursecate.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekCoursecate selectOneByExample(GeekCoursecateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekCoursecate selectOneByExampleSelective(@Param("example") GeekCoursecateExample example, @Param("selective") GeekCoursecate.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekCoursecate selectOneByExampleWithBLOBs(GeekCoursecateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<GeekCoursecate> selectByExampleSelective(@Param("example") GeekCoursecateExample example, @Param("selective") GeekCoursecate.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     */
    List<GeekCoursecate> selectByExampleWithBLOBs(GeekCoursecateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     */
    List<GeekCoursecate> selectByExample(GeekCoursecateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GeekCoursecate selectByPrimaryKeySelective(@Param("cateId") Integer cateId, @Param("selective") GeekCoursecate.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     */
    GeekCoursecate selectByPrimaryKey(Integer cateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") GeekCoursecate record, @Param("example") GeekCoursecateExample example, @Param("selective") GeekCoursecate.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") GeekCoursecate record, @Param("example") GeekCoursecateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GeekCoursecate record, @Param("example") GeekCoursecateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") GeekCoursecate record, @Param("selective") GeekCoursecate.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GeekCoursecate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GeekCoursecate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GeekCoursecate> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geek_coursecate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GeekCoursecate> list, @Param("selective") GeekCoursecate.Column ... selective);
}